2024-12-10 15:50:09 | INFO     | __main__:__init__:149 - Initializing AutoOrderService
2024-12-10 15:50:09 | INFO     | __main__:add_account:97 - Added account 15558581380 to pool
2024-12-10 15:50:09 | INFO     | __main__:add_account:97 - Added account 15557551903 to pool
2024-12-10 15:50:09 | INFO     | __main__:load_accounts:181 - Successfully loaded 2 accounts
2024-12-10 15:50:09 | DEBUG    | __main__:add_proxy:123 - Added proxy 127.0.0.1:7890 to pool
2024-12-10 15:50:09 | DEBUG    | __main__:add_proxy:123 - Added proxy 127.0.0.1:7890 to pool
2024-12-10 15:50:09 | INFO     | __main__:load_proxies:199 - Successfully loaded 2 proxies
2024-12-10 15:50:09 | INFO     | __main__:initialize_account_sessions:206 - Initializing account sessions and assigning proxies
2024-12-10 15:50:09 | ERROR    | __main__:initialize_account_sessions:228 - Failed to initialize session for account 15558581380
Traceback (most recent call last):

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2252, in <module>
    main()
    └ <function main at 0x12d391e50>

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2234, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 49858, 'vm_type': None, 'client': '127.0.0.1', 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': Fal...
              │        └ <function PyDB.run at 0x12d390e50>
              └ <__main__.PyDB object at 0x12d3765b0>

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1544, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x12d390ee0>
           └ <__main__.PyDB object at 0x12d3765b0>

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py'
    │             └ <function execfile at 0x11d3ccf70>
    └ <module '_pydev_bundle.pydev_imports' from '/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pyd...

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py'
                 └ 'from loguru import logger\nimport sys\nimport time\nfrom typing import List, Dict, Optional\nfrom dataclasses import datacla...

  File "/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py", line 626, in <module>
    service = AutoOrderService(ACCOUNTS_FILE, PROXIES_FILE, CHECK_INTERVAL)
              │                │              │             └ 30
              │                │              └ 'proxies.txt'
              │                └ 'accounts.txt'
              └ <class '__main__.AutoOrderService'>

  File "/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py", line 160, in __init__
    self.initialize_account_sessions()
    │    └ <function AutoOrderService.initialize_account_sessions at 0x12f4db670>
    └ <__main__.AutoOrderService object at 0x12f4703a0>

> File "/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py", line 211, in initialize_account_sessions
    account.session.headers.update(self.base_headers)
    │       │       │       │      └ <__main__.AutoOrderService object at 0x12f4703a0>
    │       │       │       └ <function MutableMapping.update at 0x104fc3ee0>
    │       │       └ {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-a...
    │       └ <requests.sessions.Session object at 0x12f4eb100>
    └ Account(phone='15558581380', password='gbaycm123', session=<requests.sessions.Session object at 0x12f4eb100>, proxy=None, is_...

AttributeError: 'AutoOrderService' object has no attribute 'base_headers'
2024-12-10 15:50:09 | ERROR    | __main__:initialize_account_sessions:228 - Failed to initialize session for account 15557551903
Traceback (most recent call last):

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2252, in <module>
    main()
    └ <function main at 0x12d391e50>

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2234, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 49858, 'vm_type': None, 'client': '127.0.0.1', 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': Fal...
              │        └ <function PyDB.run at 0x12d390e50>
              └ <__main__.PyDB object at 0x12d3765b0>

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1544, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x12d390ee0>
           └ <__main__.PyDB object at 0x12d3765b0>

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py'
    │             └ <function execfile at 0x11d3ccf70>
    └ <module '_pydev_bundle.pydev_imports' from '/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pyd...

  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py'
                 └ 'from loguru import logger\nimport sys\nimport time\nfrom typing import List, Dict, Optional\nfrom dataclasses import datacla...

  File "/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py", line 626, in <module>
    service = AutoOrderService(ACCOUNTS_FILE, PROXIES_FILE, CHECK_INTERVAL)
              │                │              │             └ 30
              │                │              └ 'proxies.txt'
              │                └ 'accounts.txt'
              └ <class '__main__.AutoOrderService'>

  File "/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py", line 160, in __init__
    self.initialize_account_sessions()
    │    └ <function AutoOrderService.initialize_account_sessions at 0x12f4db670>
    └ <__main__.AutoOrderService object at 0x12f4703a0>

> File "/Users/Zhuanz/Desktop/projects/6kmini_program_crawler/project/test.py", line 211, in initialize_account_sessions
    account.session.headers.update(self.base_headers)
    │       │       │       │      └ <__main__.AutoOrderService object at 0x12f4703a0>
    │       │       │       └ <function MutableMapping.update at 0x104fc3ee0>
    │       │       └ {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-a...
    │       └ <requests.sessions.Session object at 0x12f4eb340>
    └ Account(phone='15557551903', password='qweasdzxc123', session=<requests.sessions.Session object at 0x12f4eb340>, proxy=None, ...

AttributeError: 'AutoOrderService' object has no attribute 'base_headers'
2024-12-10 15:50:36 | WARNING  | __main__:<module>:626 - Service stopped by user
